# Generated by Django 3.0.2 on 2020-01-04 08:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contragent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excell_name', models.CharField(max_length=255)),
                ('dadata_name', models.CharField(max_length=255)),
                ('debt', models.FloatField(default=0.0)),
                ('inn', models.IntegerField(blank=True, null=True)),
                ('ogrn', models.IntegerField(blank=True, null=True)),
                ('kpp', models.IntegerField(blank=True, null=True)),
                ('rs', models.CharField(blank=True, max_length=255, null=True, verbose_name='Р/с')),
                ('ks', models.CharField(blank=True, max_length=255, null=True, verbose_name='К/с')),
                ('bank', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование банка')),
                ('bik', models.CharField(blank=True, max_length=255, null=True, verbose_name='БИК')),
                ('opf', models.CharField(blank=True, max_length=255, null=True, verbose_name='ОПФ')),
                ('director_status', models.CharField(blank=True, max_length=255, null=True)),
                ('director_name', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('is_func', models.BooleanField()),
                ('okved', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_address', models.CharField(max_length=255)),
                ('legal_address', models.CharField(max_length=255)),
                ('norm_value', models.FloatField(blank=True, null=True)),
                ('stat_value', models.FloatField(blank=True, null=True)),
                ('contract_accept_date', models.DateField(default=datetime.date(2018, 7, 1))),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('nunber_contract', models.CharField(blank=True, max_length=255, null=True)),
                ('current_contract_date', models.DateTimeField(blank=True, null=True)),
                ('platform', models.IntegerField(blank=True, null=True)),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current', to=settings.AUTH_USER_MODEL)),
                ('signed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
