# Generated by Django 3.0.2 on 2020-01-04 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contragent',
            name='contract_accept_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 7, 1), null=True),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='dadata_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='legal_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
