# Generated by Django 3.0.2 on 2020-01-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0002_auto_20200104_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='contragent',
            name='klass',
            field=models.CharField(choices=[(1, 'Юридическое лицо без договора'), (2, 'Юридическое лицо с договором'), (3, 'ИЖС без договора'), (4, 'ИЖС с договором'), (5, 'Физическое лицо')], default=1, max_length=255),
        ),
    ]
