# Generated by Django 3.0.2 on 2020-01-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0005_auto_20200109_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contragent',
            name='inn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
