# Generated by Django 3.0.2 on 2020-01-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebird', '0006_auto_20200110_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contragent',
            name='kpp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='ogrn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
